spring:
  application:
    name: tasks-manage
  profiles:
    active: dev
  main:
    banner-mode: "console"
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_manage_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public

logging:
  level:
    root: INFO
    com.example.tasksmanage: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  port: 8080
